<?php
$_lang['msgiftcards_prop_field_infosnippet_desc'] = 'Snippet name used to render certificate info block.';
$_lang['msgiftcards_prop_field_tpl_desc'] = 'Chunk name for msGiftCardsField markup.';
$_lang['msgiftcards_prop_field_tplinfo_desc'] = 'Chunk name passed to msGiftCardsInfo as `tpl`.';

$_lang['msgiftcards_prop_info_asbody_desc'] = 'Return only chunk body without outer wrapper (`1` or `0`).';
$_lang['msgiftcards_prop_info_balance_desc'] = 'Current certificate balance override value.';
$_lang['msgiftcards_prop_info_balance_after_desc'] = 'Balance after writeoff override value.';
$_lang['msgiftcards_prop_info_code_desc'] = 'Certificate code override value.';
$_lang['msgiftcards_prop_info_currency_desc'] = 'Currency override value (for example: RUB, USD).';
$_lang['msgiftcards_prop_info_nominal_desc'] = 'Certificate nominal override value.';
$_lang['msgiftcards_prop_info_tpl_desc'] = 'Chunk name for msGiftCardsInfo markup.';
$_lang['msgiftcards_prop_info_writeoff_desc'] = 'Writeoff amount override value.';

$_lang['msgiftcards_prop_orderdata_order_id_desc'] = 'Order ID for certificate data lookup.';
$_lang['msgiftcards_prop_orderdata_mode_desc'] = 'Selection mode: `all`, `issued`, or `redeemed`.';
$_lang['msgiftcards_prop_orderdata_format_desc'] = 'Output format: `auto`, `json` or `array` (`auto` returns array in Fenom and JSON in standard parser).';
$_lang['msgiftcards_prop_orderdata_to_placeholder_desc'] = 'If set, puts result into this MODX placeholder.';
$_lang['msgiftcards_prop_orderdata_include_issued_redemptions_desc'] = 'Include redemptions list for issued certificates (`1`/`0`).';

$_lang['msgiftcards_prop_certificate_link_order_id_desc'] = 'Order ID used to generate a protected certificate URL.';
$_lang['msgiftcards_prop_certificate_link_to_placeholder_desc'] = 'If set, stores generated certificate URL into this MODX placeholder.';
$_lang['msgiftcards_prop_certificate_link_format_desc'] = 'Output link target format: `pdf` or `html`.';
$_lang['msgiftcards_prop_certificate_link_tpl_desc'] = 'Optional chunk/@FILE template name passed to certificate.php.';

$_lang['msgiftcards_prop_certificate_html_order_id_desc'] = 'Order ID of the order that issued the certificate.';
$_lang['msgiftcards_prop_certificate_html_token_desc'] = 'Protected token generated by msGiftCardsCertificateLink. Used instead of plain order ID.';
$_lang['msgiftcards_prop_certificate_html_tpl_desc'] = 'Chunk name or @FILE template used to render certificate HTML.';
$_lang['msgiftcards_prop_certificate_html_to_placeholder_desc'] = 'If set, stores rendered certificate HTML into this MODX placeholder.';
